
<!-- Start Footer Area -->
<footer id="footer-area">
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-12">
                <div class="footer-content">
                    <h1>Use it free!</h1>
                    <p>“Conquer is free Bootstrap template from templatemo website.
                        <br>No backlink is required to use this layout.”</p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <p class="copy">Copyright © 2084 Your Company Name

                    | Design: <a rel="nofollow" href="http://www.templatemo.com" target="_parent">template mo</a></p>
            </div>
        </div>
    </div>
</footer>
<!-- End Footer Area -->
