<?php 

if($this->user){

?>
<div class="navbar navbar-default navbar-fixed-top navbar-size-large navbar-size-xlarge paper-shadow" data-z="0"
     data-animated role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand navbar-brand-logo">
                <a class="svg" href="#">
                    <img src="<?php echo $this->baseUrl(); ?>/static/img/feedIcon.png">
                </a>
            </div>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="main-nav">
            <ul class="nav navbar-nav navbar-nav-margin-left">
                <li class="dropdown">
                    <a href="<?php echo $this->baseUrl(); ?>/user/editprofile">Profile</a>
                    
                </li>
                <li class="dropdown ">
                    <a href="<?php echo $this->baseUrl(); ?>/rss/list" >View Rss</a>

                </li>
                <li class="dropdown ">
                    <a href="<?php echo $this->baseUrl(); ?>/rss/add" >Add Rss</a>

                </li>

            </ul>
            <div class="navbar-right">
                <ul class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
                    <!-- user -->
                    <li class="dropdown user">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="<?php echo $this->baseUrl(); ?>/uploads/<?php echo $this->user->photo;?>" alt="" class="img-circle"/> <?php echo Zend_Session::namespaceGet('user')['user'][0]['username'];?><span
                                class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                            <a href="<?php echo $this->baseUrl(); ?>/rss/list" >ListRss</a>

                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/rss/add" >Add Rss</a>

                            </li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/user/editprofile"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/user/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                        </ul>
                    </li>
                    <!-- // END user -->
                </ul>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</div>
<br><br><br><br><br><br><br><br>
<?php
}
else{

}


 ?>