<!DOCTYPE html>
<html  >
<head>
    <title>Rss</title>
    <!--
    Conquer Template
    http://www.templatemo.com/tm-476-conquer
    -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/static/css/style.css">
    <link href="<?php echo $this->baseUrl(); ?>/static/css/vendor.min.css" rel="stylesheet">

    <link href="<?php echo $this->baseUrl(); ?>/static/css/theme-core.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-essentials.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-material.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-layout.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-sidebar.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-sidebar-skins.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-navbar.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-messages.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-carousel-slick.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-charts.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-maps.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-colors-alerts.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-colors-background.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-colors-buttons.min.css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/static/css/module-colors-text.min.css" rel="stylesheet" />
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
<div class="transition-navbar-scroll top-navbar-xlarge bottom-footer">


<?php echo $this->render('header.phtml') ?>

<div id="content"><?php echo $this->layout()->content ?></div>

<?php //echo $this->render('footer.phtml') ?>

<script src="<?php echo  $this->baseUrl() ;?>/static/js/jquery-1.11.2.min.js"></script>
<script src="<?php echo  $this->baseUrl() ;?>/static/js/jquery.scrollUp.min.js"></script> <!-- https://github.com/markgoodyear/scrollup -->
<script src="<?php echo  $this->baseUrl() ;?>/static/js/jquery.singlePageNav.min.js"></script> <!-- https://github.com/ChrisWojcik/single-page-nav -->
<script src="<?php echo  $this->baseUrl() ;?>/static/js/parallax.js-1.3.1/parallax.js"></script> <!-- http://pixelcog.github.io/parallax.js/ -->


<script>
    var colors = {
        "danger-color": "#e74c3c",
        "success-color": "#81b53e",
        "warning-color": "#f0ad4e",
        "inverse-color": "#2c3e50",
        "info-color": "#2d7cb5",
        "default-color": "#6e7882",
        "default-light-color": "#cfd9db",
        "purple-color": "#9D8AC7",
        "mustard-color": "#d4d171",
        "lightred-color": "#e15258",
        "body-bg": "#f6f6f6"
    };
    var config = {
        theme: "html",
        skins: {
            "default": {
                "primary-color": "#42a5f5"
            }
        }
    };
</script>
<!-- Separate Vendor Script Bundles -->
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-core.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-countdown.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-tables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-forms.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-carousel-slick.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-player.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-charts-flot.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/vendor-nestable.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-essentials.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-material.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-layout.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-sidebar.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-carousel-slick.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-player.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-messages.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/module-charts-flot.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/static/js/theme-core.min.js"></script>
    </div>
</body>
</html>
