<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="login hide-sidebar ls-bottom-footer row">
	<div id="content" class=" col-lg-offset-3 col-lg-6">
		<div class="container-fluid">
			<div class="lock-container">
				<div class="panel panel-default text-center paper-shadow" data-z="0.5">
					<h1 class="text-display-1 text-center margin-bottom-none">Sign In</h1>
					<img src="<?php echo $this->baseUrl(); ?>/static/img/people/110/guy-5.jpg" class="img-circle width-80">
					<form method="post">
						<div class="panel-body">
							<div class="form-group">
								<div class="form-control-material">
									<input class="form-control" id="username" type="text" name="username" placeholder="Username">
									<label for="username">Username</label>
								</div>
							</div>
							<div class="form-group">
								<div class="form-control-material">
									<input class="form-control" id="password" type="password" name="password" placeholder="Enter Password">
									<label for="password">Password</label>
								</div>
							</div>
							<input type="submit" value="Login" class="btn btn-primary "/>
							<!-- <a href="#" class="forgot-password">Forgot password?</a>-->
							<a href="add" class="forgot-password">Create account</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

</div>
