   
<div class="st-layout ls-top-navbar-large ls-bottom-footer show-sidebar sidebar-l3" >
<div class="sidebar left sidebar-size-3 sidebar-offset-0 sidebar-visible-desktop sidebar-visible-mobile sidebar-skin-dark" id="sidebar-menu" data-type="collapse">
            <div data-scrollable>
                <div class="sidebar-block">
                    <div class="profile">
                        <a href="#">
                            <img src="images/people/110/guy-6.jpg" alt="people" class="img-circle width-80" />
                        </a>
                        <h4 class="text-display-1 margin-none">Student Name</h4>
                    </div>
                </div>
            </div>
        </div>
        <!-- sidebar effects OUTSIDE of st-pusher: -->
        <!-- st-effect-1, st-effect-2, st-effect-4, st-effect-5, st-effect-9, st-effect-10, st-effect-11, st-effect-12, st-effect-13 -->
        <!-- content push wrapper -->
        <div class="st-pusher" id="content">
            <!-- sidebar effects INSIDE of st-pusher: -->
            <!-- st-effect-3, st-effect-6, st-effect-7, st-effect-8, st-effect-14 -->
            <!-- this is the wrapper for the content -->
            <div class="st-content">
                <!-- extra div for emulating position:fixed of the menu -->
                <div class="st-content-inner padding-none">
                    <div class="container-fluid">
                        <div class="page-section third">
                            <!-- Tabbable Widget -->
                            <div class="tabbable paper-shadow relative" data-z="0.5">
                                <!-- Tabs -->
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="app-student-profile.html"><i class="fa fa-fw fa-lock"></i> <span class="hidden-sm hidden-xs">Manage Account</span></a></li>
                                </ul>
                                <!-- // END Tabs -->
                                <!-- Panes -->
                                <div class="tab-content">
                                    <div id="account" class="tab-pane active">
                                        <form class="form-horizontal" action="/user/edit/id/<?php echo $this->user->id; ?>">
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Avatar</label>
                                                <div class="col-md-6">
                                                    <div class="media v-middle">
                                                        <div class="media-left">
                                                            <div class="icon-block width-100 bg-grey-100">
                                                                
                                                                    <img src="/uploads/<?php echo $this->user->photo; ?>">
                                                            </div>
                                                        </div>
                                                       
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-md-2 control-label">Full Name</label>
                                                <div class="col-md-8">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <div class="form-control-material">
                                                                <input type="email" class="form-control" id="exampleInputFirstName" placeholder="Your first name" >
                                                                <label for="exampleInputFirstName"><?php echo $this->user->name; ?></label>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="form-control-material">
                                                                <input type="email" class="form-control" id="exampleInputLastName" placeholder="Your last name">
                                                                <label for="exampleInputLastName"><?php echo $this->user->username; ?> </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-md-2 control-label">Email</label>
                                                <div class="col-md-6">
                                                    <div class="form-control-material">
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                                            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                                                            <label for="inputEmail3"><?php echo $this->user->email; ?></label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-md-2 control-label">Gender</label>
                                                   <div class="col-md-6">
                                                            <div class="form-control-material">
                                                                <input type="email" class="form-control" id="exampleInputLastName" placeholder="Your Gender">
                                                                <label for="exampleInputLastName"><?php echo $this->user->gender; ?> </label>
                                                            </div>
                                                        </div>
                                            </div>
                                            <div class="form-group margin-none">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <button type="submit" class="btn btn-primary paper-shadow relative" data-z="0.5" data-hover-z="1" data-animated>Edit</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <!-- // END Panes -->
                            </div>
                            <!-- // END Tabbable Widget -->
                        </div>
                    </div>
                </div>
                <!-- /st-content-inner -->
            </div>
            <!-- /st-content -->
        </div>
        <!-- /st-pusher -->
        <!-- Footer -->
        <footer class="footer">
            <strong>Learning</strong> v1.0.0 &copy; Copyright 2015
        </footer>
        <!-- // Footer -->
    </div>
   </div>